/*
 * PWM1.h
 *
 * Created: 14/04/2026 08:11:37
 *  Author: aleja
 */ 


#ifndef PWM1_H_
#define PWM1_H_


#include <avr/io.h>

// CONSTANTES PARA EL MODO INVERTIDO Y NO INVERTIDO 

#define INVERTIDO 1 
#define NO_INVERTIDO 0 

// ALGUNOS MODOS DE OPERACIÓN DEL TIMER1, LOS MÁS ÚTILES PARA CONTROLAR UN SERVO MOTOR 

#define MODO_FAST_PWM_ICR 0 // MODO 14: FAST PWM, TOP = ICR1 
#define MODO_FAST_PWM_OCR 1 // MODO 15: FAST PWM, TOP = OCR1A 
#define MODO_PHASE_CORRECT 2 // MODO 8: PHASE CORRECT, TOP = ICR1 

// INICIALIZACIÓN DEL CANAL A DEL TIMER1 (OC1A) CON SUS RESPECTIVOS PARÁMETROS CONFIGURABLES 

void initPWM1A(uint8_t invertido, uint8_t modo, uint16_t prescaler, uint16_t top);

// INICIALIZACIÓN DEL CANAL B DEL TIMER1 (OC1B) CON SUS RESPECTIVOS PARÁMETROS CONFIGURABLES  

void initPWM1B(uint8_t invertido, uint8_t modo, uint16_t prescaler, uint16_t top);

// ACTUALIÇAZIÓN EL CICLO DE TRABAJO DEL CANAL A DONDE "valor" ES EL VALOR DE COMPARACIÓN (0 A TOP)

void updateDutyCycle1A(uint16_t valor);

// ACTUALIÇAZIÓN EL CICLO DE TRABAJO DEL CANAL B DONDE "valor" ES EL VALOR DE COMPARACIÓN (0 A TOP)

void updateDutyCycle1B(uint16_t valor);

// ESTABLECE EL VALOR DE TOP DONDE "top" ES EL NUEVO VALOR DE ICR1 (SI EL MODO LO SOPORTA) 

void setTop1(uint16_t top);

#endif /* PWM1_H_ */